name: Daily API Request

on:
  schedule:
    - cron: "0 13 * * 1-5" # lunes a viernes a las 13:00 UTC (~09:00 Chile)
  workflow_dispatch: {}

jobs:
  request:
    runs-on: ubuntu-latest
    concurrency:
      group: daily-request
      cancel-in-progress: true

    steps:
      - name: Build JSON (Chile TZ)
        run: |
          YEAR=$(TZ="America/Santiago" date +"%Y")
          PREV_MONTH=$(TZ="America/Santiago" date -d "-1 month" +"%-m")
          PREV_DAY=$(TZ="America/Santiago" date -d "-1 day" +"%-d")

          cat > payload.json <<EOF
          [
            [
              {
                "idUsuario": "${{ secrets.DNI }}",
                "day": $PREV_DAY,
                "month": $PREV_MONTH,
                "year": $YEAR,
                "horaEntrada": "08:00",
                "horaSalida": "18:00",
                "dayClass": "imputacionNormal"
              }
            ],
            []
          ]
          EOF

          echo "✅ JSON generado:"
          cat payload.json

      - name: Call API
        run: |
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
            -X POST "https://iaweb.atmira.com/ia-api/schedule/save" \
            -H "Accept: application/json, text/plain, */*" \
            -H "Content-Type: application/json" \
            -H "Matricula: ${{ secrets.MATRICULA }}" \
            -H "dni: ${{ secrets.DNI }}" \
            -b "cookiesession1=${{ secrets.COOKIE }}" \
            --data-binary @payload.json)

          echo "HTTP status: $RESPONSE"

          if [ "$RESPONSE" -lt 200 ] || [ "$RESPONSE" -ge 300 ]; then
            echo "❌ Request failed"
            cat response.json || true
            exit 1
          fi

          echo "✅ Request successful"
          cat response.json || true
