name: Daily API Request

on:
  schedule:
    - cron: "0 13 * * 1-5" # lunes a viernes a las 13:00 UTC (~09:00 Chile)
  workflow_dispatch: {}

jobs:
  request:
    runs-on: ubuntu-latest
    concurrency:
      group: daily-request
      cancel-in-progress: true

    steps:
      - name: Build JSON (Chile TZ)
        run: |
          YEAR=$(TZ="America/Santiago" date +"%Y")
          PREV_MONTH=$(TZ="America/Santiago" date -d "-1 month" +"%-m")
          PREV_DAY=$(TZ="America/Santiago" date -d "-1 day" +"%-d")

          cat > payload_base.json <<EOF
          [
            [
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 0,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionNormal",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 1,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionNormal",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 2,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionNormal",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 3,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionNormal",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 4,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:30",
                  "dayClass": "imputacionNormal",
                  "editable": true,
                  "diferencia": "10:30"
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 5,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionFestivo",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 6,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionFestivo",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 7,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionNormal",
                  "editable": true,
                  "horaEntradaDefault": "08:00",
                  "horaSalidaDefault": "17:30"
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 8,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionNormal",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 9,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionNormal",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 10,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionNormal",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 11,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionNormal",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 12,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionFestivo",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 13,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionFestivo",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 14,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionNormal",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 15,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionNormal",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 16,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionNormal",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 17,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionNormal",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 18,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionNormal",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 19,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionFestivo",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 20,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionFestivo",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 21,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionNormal",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 22,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionNormal",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 23,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionNormal",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 24,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionNormal",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 25,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionNormal",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 26,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionFestivo",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 27,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionFestivo",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 28,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionNormal",
                  "editable": true
              },
              {
                  "idUsuario": "${{ secrets.DNI }}",
                  "day": 29,
                  "month": $PREV_MONTH,
                  "year": $YEAR,
                  "horaEntrada": "08:00",
                  "horaSalida": "18:00",
                  "dayClass": "imputacionNormal",
                  "editable": true
              }
            ],
            []
          ]
          EOF

          echo "✅ JSON generado:"
          cat payload_base.json

      - name: Call API for each user
        run: |
          USERS_JSON='${{ secrets.USERS_JSON }}'

          echo "Iterando sobre usuarios..."
          echo "$USERS_JSON" | jq -c '.[]' | while read user; do
            DNI=$(echo $user | jq -r '.dni')
            MATRICULA=$(echo $user | jq -r '.matricula')

            echo "➡️ Enviando request para DNI=$DNI, Matricula=$MATRICULA"

            # Crear payload específico reemplazando el placeholder
            sed "s/DNI_PLACEHOLDER/$DNI/" payload_base.json > payload.json

            RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
              -X POST "https://iaweb.atmira.com/ia-api/schedule/save" \
              -H "Accept: application/json, text/plain, */*" \
              -H "Content-Type: application/json" \
              -H "Matricula: $MATRICULA" \
              -H "dni: $DNI" \
              -b "cookiesession1=${{ secrets.COOKIE }}" \
              --data-binary @payload.json)

            echo "HTTP status: $RESPONSE"

            if [ "$RESPONSE" -lt 200 ] || [ "$RESPONSE" -ge 300 ]; then
              echo "❌ Request failed para DNI=$DNI"
              cat response.json || true
              exit 1
            fi

            echo "✅ Request successful para DNI=$DNI"
            cat response.json || true
          done
