name: Daily API Request

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch: {}

jobs:
  request:
    runs-on: ubuntu-latest
    concurrency:
      group: daily-request
      cancel-in-progress: true

    steps:
      - name: Build dynamic JSON (Chile TZ)
        id: build
        run: |
          # Fechas en zona horaria de Santiago
          YEAR=$(TZ="America/Santiago" date +"%Y")
          PREV_MONTH=$(TZ="America/Santiago" date -d "-1 month" +"%-m")
          PREV_DAY=$(TZ="America/Santiago" date -d "-1 day" +"%-d")

          # JSON exacto que requiere tu API
          BODY=$(cat <<EOF
          [
            [
              {
                "idUsuario": "${{ secrets.DNI }}",
                "day": $PREV_DAY,
                "month": $PREV_MONTH,
                "year": $YEAR,
                "horaEntrada": "08:00",
                "horaSalida": "18:00",
                "dayClass": "imputacionNormal"
              }
            ],
            []
          ]
          EOF
          )

          # Exportar como output multilínea
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Call API
        run: |
          echo "Payload enviado:"
          echo "${{ steps.build.outputs.body }}"

          RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
            -X POST "https://iaweb.atmira.com/ia-api/schedule/save" \
            -H "Accept: application/json, text/plain, */*" \
            -H "Content-Type: application/json" \
            -H "Matricula: ${{ secrets.MATRICULA }}" \
            -H "dni: ${{ secrets.DNI }}" \
            -b "cookiesession1=${{ secrets.COOKIE }}" \
            -d "${{ steps.build.outputs.body }}")

          echo "HTTP status: $RESPONSE"

          if [ "$RESPONSE" -lt 200 ] || [ "$RESPONSE" -ge 300 ]; then
            echo "❌ Request failed"
            cat response.json || true
            exit 1
          fi

          echo "✅ Request successful"
          cat response.json || true
